import Head from 'next/head'
import "animate.css";
import AboutPage from '@/components/about-page/AboutPage';


export default function About() {
    return (
        <div className='animate__animated animate__fadeIn'>
        <Head>
            <title>About Page | Sero construction</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main>
           <AboutPage />
        </main>
    </div>
    )  
}