import Head from 'next/head'
import Homepage from '@/components/homepage/Homepage'
import "animate.css";


export default function Home() {
  return (
    <div className='animate__animated animate__fadeIn'>
      <Head>
        <title>Homepage | Sero construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
          <Homepage />
      </main>
    </div>
  )
}
