import ContactUsPage from "@/components/contact-us-page/ContactUsPage";
import Head from "next/head";



export default function ContactUs() {
    return (
      <div className='animate__animated animate__fadeIn'>
        <Head>
        <title>Contact Us Page | Sero construction</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main>
            <ContactUsPage />
        </main>
      </div>
    )
  }
